import py3Dmol
from type import *
from Label import Label
def to_getattr(outer):
    def inner(self,*args,**kwargs):
        self.__getattr__(outer.__name__)(*args, **kwargs)
        outer(*args,**kwargs)
    return inner

class view(py3Dmol.view):
    def __init__(self,*args,**kwargs):
        super(view, self).__init__(*args,**kwargs)
    @to_getattr
    def addArrow(self,spec:ArrowSpec):...
    @to_getattr
    def addAsOneMolecule(self,data:string,format:string):...
    @to_getattr
    def addBox(self,spec:BoxSpec):...

    @to_getattr
    def addCurve(self,spec:CurveSpec):...

    @to_getattr
    def addCustom(self,spec:CustomShapeSpec):...

    @to_getattr
    def addCylinder(self,spec:CylinderSpec):...

    @to_getattr
    def addIsosurface(self,data:VolumeData,spec:IsoSurfaceSpec):...

    @to_getattr
    def addLabel(self,text:string,options:LabelSpec,sel:AtomSelectionSpec,noshow:boolean):...

    @to_getattr
    def addLine(self,spec:LineSpec):...

    @to_getattr
    def addMesh(self,mesh:Mesh,style:Object):...

    @to_getattr
    def addModel(self,data:string,format:string,options:ParserOptionsSpec=None):...

    @to_getattr
    def addModels(self,data:string,format:string):...

    @to_getattr
    def addModelsAsFrames(self,data:string,format:string):...

    @to_getattr
    def addPropertyLabels(self,prop:string,sel:Object,style:Object):...

    @to_getattr
    def addResLabels(self,sel:Object,style:Object,byframe:boolean):...

    @to_getattr
    def addShape(self,shapeSpec:ShapeSpec):...

    @to_getattr
    def addSphere(self,spec:SphereShapeSpec):...

    @to_getattr
    def addStyle(self,sel:AtomSelectionSpec,style:AtomStyleSpec):...

    @to_getattr
    def addSurface(self,type:SurfaceType,style:SurfaceStyleSpec,atomsel:AtomSelectionSpec,
                   allsel:AtomSelectionSpec,focus:AtomSelectionSpec,surfacecallback:function):...

    @to_getattr
    def addUnitCell(self,model:GLModel,spec:UnitCellStyleSpec):...

    # TODO: need to be attention of [my]or here
    @to_getattr
    def addVolumetricData(self,data:string,format:string,myor:IsoSurfaceSpec):...

    @to_getattr
    def addVolumetricRender(self,data:VolumeData, spec:VolumetricRendererSpec):...

    @to_getattr
    def animate(self,options:Object):...

    @to_getattr
    def center(self,sel:Object,animationDuration:number,fixedPath:boolean):...

    @to_getattr
    def clear(self):...

    @to_getattr
    def createModelFrom(self,sel:Object,extract:boolean):...

    @to_getattr
    def enableFog(self,fog:boolean):...

    @to_getattr
    def exportJSON(self,includeStyles:boolean,modelID:number):...

    @to_getattr
    def exportVRML(self):...

    @to_getattr
    def fitSlab(self,sel:Object):...

    @to_getattr
    def getFrame(self):...

    @to_getattr
    def getInternalState(self):...

    @to_getattr
    def getModel(self,id:number):...

    @to_getattr
    def getNumFrames(self):...

    @to_getattr
    def getPerceivedDistance(self):...

    @to_getattr
    def getSlab(self,near:number,far:number):...

    @to_getattr
    def getView(self):...

    @to_getattr
    def hasVolumetricRender(self):...

    @to_getattr
    def isAnimated(self):...

    @to_getattr
    def _linkViewer(self):...

    @to_getattr
    def mapAtomProperties(self,props:Object,sel:AtomSelectionSpec):...

    # @to_getattr
    # def modelToScreen(self,coor:Union[Object,List[Object]]):...

    @to_getattr
    def pdbData(self,sel:Object):...

    @to_getattr
    def pngURI(self):...

    @to_getattr
    def removeAllLabels(self):...

    @to_getattr
    def removeAllModels(self):...

    @to_getattr
    def removeAllShapes(self):...

    @to_getattr
    def removeAllSurfaces(self):...

    @to_getattr
    def removeLabel(self,label:Label):...

    @to_getattr
    def removeModel(self,model:GLModel):...

    @to_getattr
    def removeShape(self,shape:GLShape):...

    @to_getattr
    def removeSurface(self,surf:number):...

    @to_getattr
    def removeUnitCell(self,model:GLModel):...

    @to_getattr
    def render(self):...

    @to_getattr
    def replicateUnitCell(self,A:int,B:int,C:int,model:GLModel):...

    @to_getattr
    def resize(self):...

    @to_getattr
    def rotate(self,angle:number,axis:string,animationDuration:number,fixedPath:boolean):...

    @to_getattr
    def screenOffsetToModel(self):...

    @to_getattr
    def screenToModelDistance(self):...

    @to_getattr
    def selectToModelDistance(self):...

    @to_getattr
    def selectAtoms(self,sel:AtomSelectionSpec):...

    @to_getattr
    def setAutoEyeSeparation(self):...

    @to_getattr
    def setBackgroundColor(self,hex:number,a:number):...

    @to_getattr
    def setCameraParameters(self,parameters):...

    @to_getattr
    def setClickable(self,sel:AtomSelectionSpec, clickable:boolean, callback:function):...

    @to_getattr
    def setColorByElement(self,sel:AtomSelectionSpec, colors:ColorSpec):...

    @to_getattr
    def setColorByProperty(sel, prop,scheme):...

    # @to_getattr
    # def setContainer(self,element:Union[Object,string]):...

    @to_getattr
    def setDefaultCartoonQuality(self):...

    @to_getattr
    def setFrame(self,framenum:number):...

    @to_getattr
    def setHeight(self,h:number):...

    @to_getattr
    def setHoverable(self,sel:AtomSelectionSpec,hoverable:boolean,
                     hover_callback:function,unhover_callback:function):...

    @to_getattr
    def setHoverDuration(self,hoverDuration:number):...

    @to_getattr
    def setInternalState(self):...

    @to_getattr
    def setLabelStyle(self,label:Label, stylespec:Object):...

    @to_getattr
    def setLabelText(self,label:Label, text:string):...

    @to_getattr
    def setPerceivedDistance(self):...

    @to_getattr
    def setProjection(self,set="orthographic"):...

    @to_getattr
    def setSlab(self,near:number,far:number):...

    @to_getattr
    def setStateChangeCallback(self):...

    @to_getattr
    def setStyle(self, sel:AtomSelectionSpec=dict(),style:AtomStyleSpec=dict()):...

    @to_getattr
    def setSurfaceMaterialStyle(self,surf:number, style:SurfaceStyleSpec):...

    @to_getattr
    def setView(self,arg:List[number]):...

    @to_getattr
    def setViewChangeCallback(self):...

    @to_getattr
    def setViewStyle(self,style):...

    @to_getattr
    def setWidth(self,w:number):...

    @to_getattr
    def setZoomLimits(self,lower:number,upper:number):...

    @to_getattr
    def spin(self,axis:string,speed:number):...

    @to_getattr
    def stopAnimate(self):...

    @to_getattr
    def targetedObjects(self,x:number,y:number,object):...

    @to_getattr
    def translate(self,x:number,y:number,animationDuration:number,fixedPath:boolean):...

    @to_getattr
    def translateScene(self,x:number, y:number, animationDuration:number, fixedPath:boolean):...

    @to_getattr
    def vibrate(self,numFrames:number, amplitude:number, bothWays:boolean, arrowSpec:ArrowSpec):...

    @to_getattr
    def zoom(self,factor:number, animationDuration:number, fixedPath:boolean):...

    @to_getattr
    def zoomTo(self,sel:Object, animationDuration:number, fixedPath:boolean):...









